### ISSUE TITLE
Picture is not recognized when the picture description is unicode encoded

### ISSUE THREAD

**Issue by francosolerio** [michaelnisi/MNAVChapters#10]
When the description in a picture frame is unicode encoded, we have to scan the string up to a double terminator ("\0\0"). Otherwise the scan stops at the first \0 which is often part of a two bytes encoded character, the description gets truncated too early, the scan frame is wrongly positioned and [UIImage imageWithData:content] returns nil because the data in content is dirty.

I have a fix ready, if you want I can submit a pull request.

**Comment by Hackmodford** [comment]
Go ahead, I'll take a look. Can you provide an example file as well?

**Comment by francosolerio** [comment]
You can check this file: [Digitalia493](http://dgt.fm/493.mp3) where chapter 14 "La Supremazia Quantistica" should have an associated picture. 

But basically anything rendered with [Podcast Chapters](https://chaptersapp.com) for Mac OS will fail. Here you have the auphonic_chapters_demo.mp3 file loaded and re-saved with Podcast Chapters.
[auphonic_chapters_demo.mp3.zip](https://github.com/michaelnisi/MNAVChapters/files/3799185/auphonic_chapters_demo.mp3.zip)

**Comment by michaelnisi** [comment]
Been a minute, sorry and thanks – merged with 2.0.2
